name: hello-tests-with-packages

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  # This is the name you have to search for when enabling branch protection
  # mechanisms in the repository settings. (Not mentioned in the docs as far as
  # I can tell?)
  test-ubuntu-latest-with-packages:
    runs-on: ubuntu-latest
    steps:

      - uses: dylan-lang/install-dylan-tool@v1

      - name: Create workspace
        run: |
          ./dylan new workspace hello-workspace

      # dylan-tool finds "active packages" by looking for */pkg.json directly
      # inside the workspace directory, so it's important to checkout the code
      # into a subdirectory here by using path:.
      - uses: actions/checkout@v2
        with:
          path: hello-workspace/hello

      - name: Build hello-test-suite
        run: |
          cd hello-workspace
          ../dylan update
          ../dylan-compiler -build -jobs 3 hello-test-suite

      - name: Run hello-test-suite
        run: |
          hello-workspace/_build/bin/hello-test-suite
