name: hello-tests

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      # actions/checkout must come first if using the default path since it
      # seems to delete files in the current directory.
      - uses: actions/checkout@v6

      # This puts the OD executables on the PATH.
      - uses: dylan-lang/install-opendylan@v3

      - name: Update workspace
        run: deft update

      - name: Build everything
        run: deft build --all

      - name: Run app
        run: _build/bin/hello-app

      - name: Run tests
        run: _build/bin/hello-test-suite
