name: hello-tests

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      # actions/checkout must come first if using the default path since it
      # seems to delete files in the current directory.
      - uses: actions/checkout@v4

      # This puts the latest "dylan-compiler" and "dylan" binaries in the current
      # directory.
      - uses: dylan-lang/install-opendylan@v3

      - name: Update workspace
        run: dylan update

      - name: Build test suite
        run: dylan build hello-test-suite

      - name: Run tests
        run: _build/bin/hello-test-suite
